export const ITEM_ADD_TO_CART = "ITEM_ADD_TO_CART"
export const ITEM_REMOVE_FROM_CART = "ITEM_REMOVE_FROM_CART"
export const ITEM_CART_CLEAR = "ITEM_CART_CLEAR"

export const CART_SAVE_SHIPPING_ADRESS = "CART_SAVE_SHIPPING_ADRESS"
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"
